const airforce = new Image(35,35);
const akron = new Image(35,35);
const alabama = new Image(35,35);
const appalachianstate = new Image(35,35);
const arizona = new Image(35,35);
const arizonastate = new Image(35,35);
const arkansas = new Image(35,35);
const arkansasstate = new Image(35,35);
const army = new Image(35,35);
const auburn = new Image(35,35);
const ballstate = new Image(35,35);
const baylor = new Image(35,35);
const boisestate = new Image(35,35);
const bostoncollege = new Image(35,35);
const bowlinggreen = new Image(35,35);
const buffalo = new Image(35,35);
const byu = new Image(35,35);
const california = new Image(35,35);
const centralmichigan = new Image(35,35);
const charlotte = new Image(35,35);
const cincinnati = new Image(35,35);
const clemson = new Image(35,35);
const coastalcarolina = new Image(35,35);
const colorado = new Image(35,35);
const coloradostate = new Image(35,35);
const duke = new Image(35,35);
const eastcarolina = new Image(35,35);
const easternmichigan = new Image(35,35);
const fiu = new Image(35,35);
const florida = new Image(35,35);
const floridaatlantic = new Image(35,35);
const floridastate = new Image(35,35);
const fresnostate = new Image(35,35);
const georgia = new Image(35,35);
const georgiasouthern = new Image(35,35);
const georgiastate = new Image(35,35);
const georgiatech = new Image(35,35);
const hawaii = new Image(35,35);
const houston = new Image(35,35);
const illinois = new Image(35,35);
const indiana = new Image(35,35);
const iowa = new Image(35,35);
const iowastate = new Image(35,35);
const jamesmadison = new Image(35,35);
const kansas = new Image(35,35);
const kansasstate = new Image(35,35);
const kentstate = new Image(35,35);
const kentucky = new Image(35,35);
const liberty = new Image(35,35);
const louisiana = new Image(35,35);
const louisianatech = new Image(35,35);
const louisianamonroe = new Image(35,35);
const louisville = new Image(35,35);
const lsu = new Image(35,35);
const marshall = new Image(35,35);
const maryland = new Image(35,35);
const memphis = new Image(35,35);
const miamifl = new Image(35,35);
const miamioh = new Image(35,35);
const michigan = new Image(35,35);
const michiganstate = new Image(35,35);
const middletennessee = new Image(35,35);
const minnesota = new Image(35,35);
const mississippistate = new Image(35,35);
const missouri = new Image(35,35);
const navy = new Image(35,35);
const nebraska = new Image(35,35);
const nevada = new Image(35,35);
const newmexico = new Image(35,35);
const newmexicostate = new Image(35,35);
const northcarolina = new Image(35,35);
const northcarolinastate = new Image(35,35);
const northtexas = new Image(35,35);
const northernillinois = new Image(35,35);
const northwestern = new Image(35,35);
const notredame = new Image(35,35);
const ohio = new Image(35,35);
const ohiostate = new Image(35,35);
const oklahoma = new Image(35,35);
const oklahomastate = new Image(35,35);
const olddominion = new Image(35,35);
const olemiss = new Image(35,35);
const oregon = new Image(35,35);
const oregonstate = new Image(35,35);
const pennstate = new Image(35,35);
const pittsburgh = new Image(35,35);
const purdue = new Image(35,35);
const rice = new Image(35,35);
const rutgers = new Image(35,35);
const sandiegostate = new Image(35,35);
const sanjosestate = new Image(35,35);
const smu = new Image(35,35);
const southalabama = new Image(35,35);
const southcarolina = new Image(35,35);
const southflorida = new Image(35,35);
const southernmiss = new Image(35,35);
const stanford = new Image(35,35);
const syracuse = new Image(35,35);
const tcu = new Image(35,35);
const temple = new Image(35,35);
const tennessee = new Image(35,35);
const texas = new Image(35,35);
const texasam = new Image(35,35);
const texasstate = new Image(35,35);
const texastech = new Image(35,35);
const toledo = new Image(35,35);
const troy = new Image(35,35);
const tulane = new Image(35,35);
const tulsa = new Image(35,35);
const uab = new Image(35,35);
const ucf = new Image(35,35);
const ucla = new Image(35,35);
const uconn = new Image(35,35);
const umass = new Image(35,35);
const unlv = new Image(35,35);
const usc = new Image(35,35);
const utah = new Image(35,35);
const utahstate = new Image(35,35);
const utep = new Image(35,35);
const utsa = new Image(35,35);
const vanderbilt = new Image(35,35);
const virginia = new Image(35,35);
const virginiatech = new Image(35,35);
const wakeforest = new Image(35,35);
const washington = new Image(35,35);
const washingtonstate = new Image(35,35);
const westvirginia = new Image(35,35);
const westernkentucky = new Image(35,35);
const westernmichigan = new Image(35,35);
const wisconsin = new Image(35,35);
const wyoming = new Image(35,35);

        airforce.src = 'https://alexvastartis.github.io/images/logos/airforce.svg'
akron.src = 'https://alexvastartis.github.io/images/logos/akron.svg'
alabama.src = 'https://alexvastartis.github.io/images/logos/alabama.svg'
appalachianstate.src = 'https://alexvastartis.github.io/images/logos/appalachianstate.svg'
arizona.src = 'https://alexvastartis.github.io/images/logos/arizona.svg'
arizonastate.src = 'https://alexvastartis.github.io/images/logos/arizonastate.svg'
arkansas.src = 'https://alexvastartis.github.io/images/logos/arkansas.svg'
arkansasstate.src = 'https://alexvastartis.github.io/images/logos/arkansasstate.svg'
army.src = 'https://alexvastartis.github.io/images/logos/army.svg'
auburn.src = 'https://alexvastartis.github.io/images/logos/auburn.svg'
ballstate.src = 'https://alexvastartis.github.io/images/logos/ballstate.svg'
baylor.src = 'https://alexvastartis.github.io/images/logos/baylor.svg'
boisestate.src = 'https://alexvastartis.github.io/images/logos/boisestate.svg'
bostoncollege.src = 'https://alexvastartis.github.io/images/logos/bostoncollege.svg'
bowlinggreen.src = 'https://alexvastartis.github.io/images/logos/bowlinggreen.svg'
buffalo.src = 'https://alexvastartis.github.io/images/logos/buffalo.svg'
byu.src = 'https://alexvastartis.github.io/images/logos/byu.svg'
california.src = 'https://alexvastartis.github.io/images/logos/california.svg'
centralmichigan.src = 'https://alexvastartis.github.io/images/logos/centralmichigan.svg'
charlotte.src = 'https://alexvastartis.github.io/images/logos/charlotte.svg'
cincinnati.src = 'https://alexvastartis.github.io/images/logos/cincinnati.svg'
clemson.src = 'https://alexvastartis.github.io/images/logos/clemson.svg'
coastalcarolina.src = 'https://alexvastartis.github.io/images/logos/coastalcarolina.svg'
colorado.src = 'https://alexvastartis.github.io/images/logos/colorado.svg'
coloradostate.src = 'https://alexvastartis.github.io/images/logos/coloradostate.svg'
duke.src = 'https://alexvastartis.github.io/images/logos/duke.svg'
eastcarolina.src = 'https://alexvastartis.github.io/images/logos/eastcarolina.svg'
easternmichigan.src = 'https://alexvastartis.github.io/images/logos/easternmichigan.svg'
fiu.src = 'https://alexvastartis.github.io/images/logos/fiu.svg'
florida.src = 'https://alexvastartis.github.io/images/logos/florida.svg'
floridaatlantic.src = 'https://alexvastartis.github.io/images/logos/floridaatlantic.svg'
floridastate.src = 'https://alexvastartis.github.io/images/logos/floridastate.svg'
fresnostate.src = 'https://alexvastartis.github.io/images/logos/fresnostate.svg'
georgia.src = 'https://alexvastartis.github.io/images/logos/georgia.svg'
georgiasouthern.src = 'https://alexvastartis.github.io/images/logos/georgiasouthern.svg'
georgiastate.src = 'https://alexvastartis.github.io/images/logos/georgiastate.svg'
georgiatech.src = 'https://alexvastartis.github.io/images/logos/georgiatech.svg'
hawaii.src = 'https://alexvastartis.github.io/images/logos/hawaii.svg'
houston.src = 'https://alexvastartis.github.io/images/logos/houston.svg'
illinois.src = 'https://alexvastartis.github.io/images/logos/illinois.svg'
indiana.src = 'https://alexvastartis.github.io/images/logos/indiana.svg'
iowa.src = 'https://alexvastartis.github.io/images/logos/iowa.svg'
iowastate.src = 'https://alexvastartis.github.io/images/logos/iowastate.svg'
jamesmadison.src = 'https://alexvastartis.github.io/images/logos/jamesmadison.svg'
kansas.src = 'https://alexvastartis.github.io/images/logos/kansas.svg'
kansasstate.src = 'https://alexvastartis.github.io/images/logos/kansasstate.svg'
kentstate.src = 'https://alexvastartis.github.io/images/logos/kentstate.svg'
kentucky.src = 'https://alexvastartis.github.io/images/logos/kentucky.svg'
liberty.src = 'https://alexvastartis.github.io/images/logos/liberty.svg'
louisiana.src = 'https://alexvastartis.github.io/images/logos/louisiana.svg'
louisianatech.src = 'https://alexvastartis.github.io/images/logos/louisianatech.svg'
louisianamonroe.src = 'https://alexvastartis.github.io/images/logos/louisianamonroe.svg'
louisville.src = 'https://alexvastartis.github.io/images/logos/louisville.svg'
lsu.src = 'https://alexvastartis.github.io/images/logos/lsu.svg'
marshall.src = 'https://alexvastartis.github.io/images/logos/marshall.svg'
maryland.src = 'https://alexvastartis.github.io/images/logos/maryland.svg'
memphis.src = 'https://alexvastartis.github.io/images/logos/memphis.svg'
miamifl.src = 'https://alexvastartis.github.io/images/logos/miamifl.svg'
miamioh.src = 'https://alexvastartis.github.io/images/logos/miamioh.svg'
michigan.src = 'https://alexvastartis.github.io/images/logos/michigan.svg'
michiganstate.src = 'https://alexvastartis.github.io/images/logos/michiganstate.svg'
middletennessee.src = 'https://alexvastartis.github.io/images/logos/middletennessee.svg'
minnesota.src = 'https://alexvastartis.github.io/images/logos/minnesota.svg'
mississippistate.src = 'https://alexvastartis.github.io/images/logos/mississippistate.svg'
missouri.src = 'https://alexvastartis.github.io/images/logos/missouri.svg'
navy.src = 'https://alexvastartis.github.io/images/logos/navy.svg'
nebraska.src = 'https://alexvastartis.github.io/images/logos/nebraska.svg'
nevada.src = 'https://alexvastartis.github.io/images/logos/nevada.svg'
newmexico.src = 'https://alexvastartis.github.io/images/logos/newmexico.svg'
newmexicostate.src = 'https://alexvastartis.github.io/images/logos/newmexicostate.svg'
northcarolina.src = 'https://alexvastartis.github.io/images/logos/northcarolina.svg'
northcarolinastate.src = 'https://alexvastartis.github.io/images/logos/northcarolinastate.svg'
northtexas.src = 'https://alexvastartis.github.io/images/logos/northtexas.svg'
northernillinois.src = 'https://alexvastartis.github.io/images/logos/northernillinois.svg'
northwestern.src = 'https://alexvastartis.github.io/images/logos/northwestern.svg'
notredame.src = 'https://alexvastartis.github.io/images/logos/notredame.svg'
ohio.src = 'https://alexvastartis.github.io/images/logos/ohio.svg'
ohiostate.src = 'https://alexvastartis.github.io/images/logos/ohiostate.svg'
oklahoma.src = 'https://alexvastartis.github.io/images/logos/oklahoma.svg'
oklahomastate.src = 'https://alexvastartis.github.io/images/logos/oklahomastate.svg'
olddominion.src = 'https://alexvastartis.github.io/images/logos/olddominion.svg'
olemiss.src = 'https://alexvastartis.github.io/images/logos/olemiss.svg'
oregon.src = 'https://alexvastartis.github.io/images/logos/oregon.svg'
oregonstate.src = 'https://alexvastartis.github.io/images/logos/oregonstate.svg'
pennstate.src = 'https://alexvastartis.github.io/images/logos/pennstate.svg'
pittsburgh.src = 'https://alexvastartis.github.io/images/logos/pittsburgh.svg'
purdue.src = 'https://alexvastartis.github.io/images/logos/purdue.svg'
rice.src = 'https://alexvastartis.github.io/images/logos/rice.svg'
rutgers.src = 'https://alexvastartis.github.io/images/logos/rutgers.svg'
sandiegostate.src = 'https://alexvastartis.github.io/images/logos/sandiegostate.svg'
sanjosestate.src = 'https://alexvastartis.github.io/images/logos/sanjosestate.svg'
smu.src = 'https://alexvastartis.github.io/images/logos/smu.svg'
southalabama.src = 'https://alexvastartis.github.io/images/logos/southalabama.svg'
southcarolina.src = 'https://alexvastartis.github.io/images/logos/southcarolina.svg'
southflorida.src = 'https://alexvastartis.github.io/images/logos/southflorida.svg'
southernmiss.src = 'https://alexvastartis.github.io/images/logos/southernmiss.svg'
stanford.src = 'https://alexvastartis.github.io/images/logos/stanford.svg'
syracuse.src = 'https://alexvastartis.github.io/images/logos/syracuse.svg'
tcu.src = 'https://alexvastartis.github.io/images/logos/tcu.svg'
temple.src = 'https://alexvastartis.github.io/images/logos/temple.svg'
tennessee.src = 'https://alexvastartis.github.io/images/logos/tennessee.svg'
texas.src = 'https://alexvastartis.github.io/images/logos/texas.svg'
texasam.src = 'https://alexvastartis.github.io/images/logos/texasam.svg'
texasstate.src = 'https://alexvastartis.github.io/images/logos/texasstate.svg'
texastech.src = 'https://alexvastartis.github.io/images/logos/texastech.svg'
toledo.src = 'https://alexvastartis.github.io/images/logos/toledo.svg'
troy.src = 'https://alexvastartis.github.io/images/logos/troy.svg'
tulane.src = 'https://alexvastartis.github.io/images/logos/tulane.svg'
tulsa.src = 'https://alexvastartis.github.io/images/logos/tulsa.svg'
uab.src = 'https://alexvastartis.github.io/images/logos/uab.svg'
ucf.src = 'https://alexvastartis.github.io/images/logos/ucf.svg'
ucla.src = 'https://alexvastartis.github.io/images/logos/ucla.svg'
uconn.src = 'https://alexvastartis.github.io/images/logos/uconn.svg'
umass.src = 'https://alexvastartis.github.io/images/logos/umass.svg'
unlv.src = 'https://alexvastartis.github.io/images/logos/unlv.svg'
usc.src = 'https://alexvastartis.github.io/images/logos/usc.svg'
utah.src = 'https://alexvastartis.github.io/images/logos/utah.svg'
utahstate.src = 'https://alexvastartis.github.io/images/logos/utahstate.svg'
utep.src = 'https://alexvastartis.github.io/images/logos/utep.svg'
utsa.src = 'https://alexvastartis.github.io/images/logos/utsa.svg'
vanderbilt.src = 'https://alexvastartis.github.io/images/logos/vanderbilt.svg'
virginia.src = 'https://alexvastartis.github.io/images/logos/virginia.svg'
virginiatech.src = 'https://alexvastartis.github.io/images/logos/virginiatech.svg'
wakeforest.src = 'https://alexvastartis.github.io/images/logos/wakeforest.svg'
washington.src = 'https://alexvastartis.github.io/images/logos/washington.svg'
washingtonstate.src = 'https://alexvastartis.github.io/images/logos/washingtonstate.svg'
westvirginia.src = 'https://alexvastartis.github.io/images/logos/westvirginia.svg'
westernkentucky.src = 'https://alexvastartis.github.io/images/logos/westernkentucky.svg'
westernmichigan.src = 'https://alexvastartis.github.io/images/logos/westernmichigan.svg'
wisconsin.src = 'https://alexvastartis.github.io/images/logos/wisconsin.svg'
wyoming.src = 'https://alexvastartis.github.io/images/logos/wyoming.svg'
