import type { DynastyRun } from './dynastyRuns';

/**
 * Basketball head-coach tenures for the "Apply a coach's run" picker.
 * GENERATED by scripts/basketball/build-coach-runs.mjs from data/basketball/staging —
 * don't hand-edit the numbers; change the run list there and re-run it. Totals are the
 * coach's full as-played record over the exact seasons (NCAA vacations not applied).
 * Conference titles count only seasons from 1950 on (earlier ones aren't dated).
 * Stat keys follow the shared mapping in src/config/site.ts (nflDraftPicks = Sweet 16s,
 * firstRoundPicks = Final Fours, consensusAA = first-team All-Americans,
 * unanimousAA = national players of the year).
 */
export const BASKETBALL_RUNS: DynastyRun[] = [
  {
    "id": "wooden",
    "coach": "John Wooden",
    "program": "UCLA",
    "years": "1948–75",
    "seasons": 27,
    "shape": "Ten titles in twelve years — the run nobody has come close to since",
    "tenure": {
      "allTimeWins": 620,
      "nationalTitles": 10,
      "conferenceTitles": 17,
      "consensusAA": 12,
      "unanimousAA": 5,
      "nflDraftPicks": 16,
      "firstRoundPicks": 12,
      "weeksApPoll": 246,
      "weeksApTop10": 214
    },
    "tenureWinPct": 0.808
  },
  {
    "id": "krzyzewski",
    "coach": "Mike Krzyzewski",
    "program": "Duke",
    "years": "1980–2022",
    "seasons": 42,
    "shape": "Forty-two years, five titles, thirteen Final Fours — the modern standard",
    "tenure": {
      "allTimeWins": 1133,
      "nationalTitles": 5,
      "conferenceTitles": 13,
      "consensusAA": 20,
      "unanimousAA": 8,
      "nflDraftPicks": 26,
      "firstRoundPicks": 13,
      "weeksApPoll": 664,
      "weeksApTop10": 570
    },
    "tenureWinPct": 0.778
  },
  {
    "id": "rupp",
    "coach": "Adolph Rupp",
    "program": "Kentucky",
    "years": "1930–72",
    "seasons": 41,
    "shape": "The Baron — four titles and the program every other one is measured against",
    "tenure": {
      "allTimeWins": 876,
      "nationalTitles": 4,
      "conferenceTitles": 15,
      "consensusAA": 6,
      "unanimousAA": 0,
      "nflDraftPicks": 20,
      "firstRoundPicks": 6,
      "weeksApPoll": 249,
      "weeksApTop10": 223
    },
    "tenureWinPct": 0.822
  },
  {
    "id": "smith",
    "coach": "Dean Smith",
    "program": "North Carolina",
    "years": "1961–97",
    "seasons": 36,
    "shape": "Thirty-six years, eleven Final Fours, 33 straight top-three ACC finishes",
    "tenure": {
      "allTimeWins": 879,
      "nationalTitles": 2,
      "conferenceTitles": 15,
      "consensusAA": 11,
      "unanimousAA": 1,
      "nflDraftPicks": 21,
      "firstRoundPicks": 11,
      "weeksApPoll": 503,
      "weeksApTop10": 396
    },
    "tenureWinPct": 0.776
  },
  {
    "id": "calhoun",
    "coach": "Jim Calhoun",
    "program": "UConn",
    "years": "1986–2012",
    "seasons": 26,
    "shape": "Built a blue blood out of a Big East afterthought — three titles",
    "tenure": {
      "allTimeWins": 629,
      "nationalTitles": 3,
      "conferenceTitles": 9,
      "consensusAA": 6,
      "unanimousAA": 0,
      "nflDraftPicks": 13,
      "firstRoundPicks": 4,
      "weeksApPoll": 313,
      "weeksApTop10": 193
    },
    "tenureWinPct": 0.72
  },
  {
    "id": "knight",
    "coach": "Bob Knight",
    "program": "Indiana",
    "years": "1971–2000",
    "seasons": 29,
    "shape": "Three titles, including the last unbeaten season (1976)",
    "tenure": {
      "allTimeWins": 659,
      "nationalTitles": 3,
      "conferenceTitles": 11,
      "consensusAA": 8,
      "unanimousAA": 2,
      "nflDraftPicks": 14,
      "firstRoundPicks": 5,
      "weeksApPoll": 337,
      "weeksApTop10": 176
    },
    "tenureWinPct": 0.731
  },
  {
    "id": "self",
    "coach": "Bill Self",
    "program": "Kansas",
    "years": "2003–26",
    "seasons": 23,
    "shape": "A Big 12 title nearly every year and two national championships",
    "tenure": {
      "allTimeWins": 652,
      "nationalTitles": 2,
      "conferenceTitles": 17,
      "consensusAA": 6,
      "unanimousAA": 1,
      "nflDraftPicks": 11,
      "firstRoundPicks": 4,
      "weeksApPoll": 410,
      "weeksApTop10": 311
    },
    "tenureWinPct": 0.796
  },
  {
    "id": "calipari",
    "coach": "John Calipari",
    "program": "Kentucky",
    "years": "2009–24",
    "seasons": 15,
    "shape": "One-and-done Kentucky — a title, four Final Fours, a 38-1 season",
    "tenure": {
      "allTimeWins": 410,
      "nationalTitles": 1,
      "conferenceTitles": 6,
      "consensusAA": 6,
      "unanimousAA": 2,
      "nflDraftPicks": 8,
      "firstRoundPicks": 4,
      "weeksApPoll": 241,
      "weeksApTop10": 150
    },
    "tenureWinPct": 0.769
  },
  {
    "id": "williams",
    "coach": "Roy Williams",
    "program": "North Carolina",
    "years": "2003–21",
    "seasons": 18,
    "shape": "Home to Chapel Hill — three titles in thirteen years",
    "tenure": {
      "allTimeWins": 485,
      "nationalTitles": 3,
      "conferenceTitles": 9,
      "consensusAA": 5,
      "unanimousAA": 1,
      "nflDraftPicks": 10,
      "firstRoundPicks": 5,
      "weeksApPoll": 274,
      "weeksApTop10": 180
    },
    "tenureWinPct": 0.748
  },
  {
    "id": "hurley",
    "coach": "Dan Hurley",
    "program": "UConn",
    "years": "2018–26",
    "seasons": 8,
    "shape": "Back-to-back titles and a third final in four years — eight seasons at a sprint",
    "tenure": {
      "allTimeWins": 199,
      "nationalTitles": 2,
      "conferenceTitles": 1,
      "consensusAA": 0,
      "unanimousAA": 0,
      "nflDraftPicks": 3,
      "firstRoundPicks": 3,
      "weeksApPoll": 89,
      "weeksApTop10": 52
    },
    "tenureWinPct": 0.726
  },
  {
    "id": "izzo",
    "coach": "Tom Izzo",
    "program": "Michigan State",
    "years": "1995–2026",
    "seasons": 31,
    "shape": "Thirty years of March — a title and eight Final Fours",
    "tenure": {
      "allTimeWins": 764,
      "nationalTitles": 1,
      "conferenceTitles": 11,
      "consensusAA": 4,
      "unanimousAA": 0,
      "nflDraftPicks": 17,
      "firstRoundPicks": 8,
      "weeksApPoll": 382,
      "weeksApTop10": 214
    },
    "tenureWinPct": 0.711
  },
  {
    "id": "wright",
    "coach": "Jay Wright",
    "program": "Villanova",
    "years": "2001–22",
    "seasons": 21,
    "shape": "Two titles in three years and a Big East machine",
    "tenure": {
      "allTimeWins": 520,
      "nationalTitles": 2,
      "conferenceTitles": 9,
      "consensusAA": 4,
      "unanimousAA": 1,
      "nflDraftPicks": 8,
      "firstRoundPicks": 4,
      "weeksApPoll": 251,
      "weeksApTop10": 164
    },
    "tenureWinPct": 0.725
  },
  {
    "id": "crum",
    "coach": "Denny Crum",
    "program": "Louisville",
    "years": "1971–2001",
    "seasons": 30,
    "shape": "Two titles and six Final Fours in the Metro Conference",
    "tenure": {
      "allTimeWins": 675,
      "nationalTitles": 2,
      "conferenceTitles": 14,
      "consensusAA": 3,
      "unanimousAA": 0,
      "nflDraftPicks": 16,
      "firstRoundPicks": 6,
      "weeksApPoll": 298,
      "weeksApTop10": 131
    },
    "tenureWinPct": 0.696
  },
  {
    "id": "olson",
    "coach": "Lute Olson",
    "program": "Arizona",
    "years": "1983–2007",
    "seasons": 24,
    "shape": "Made Arizona a national power — the 1997 title, 23 straight tournaments",
    "tenure": {
      "allTimeWins": 590,
      "nationalTitles": 1,
      "conferenceTitles": 10,
      "consensusAA": 6,
      "unanimousAA": 0,
      "nflDraftPicks": 11,
      "firstRoundPicks": 4,
      "weeksApPoll": 349,
      "weeksApTop10": 219
    },
    "tenureWinPct": 0.754
  },
  {
    "id": "allen",
    "coach": "Phog Allen",
    "program": "Kansas",
    "years": "1919–56",
    "seasons": 37,
    "shape": "The father of basketball coaching — the 1952 title, 24 league crowns",
    "tenure": {
      "allTimeWins": 556,
      "nationalTitles": 1,
      "conferenceTitles": 3,
      "consensusAA": 2,
      "unanimousAA": 0,
      "nflDraftPicks": 4,
      "firstRoundPicks": 3,
      "weeksApPoll": 45,
      "weeksApTop10": 21
    },
    "tenureWinPct": 0.72,
    "note": "AP-poll weeks count from 1949-50, the first season on record; All-Americans from 1949-50."
  }
];
